matrix-org/rust-synapse-compress-state

Cargo.lock
Cargo.toml
src/database.rs

`cargo outdated -R` now reports all deps are up-to-date. Minor code changes were necessary.

Cargo.toml: Update dependencies

---

.gitignore
src/graphing.rs
src/lib.rs

BUILDS ON azren/wrapped_in_pyo3 (PR #42)
Added a -g option which creates a set of 4 files:
- before_edges.csv
- before_nodes.csv
- after_edges.csv
- after_nodes.csv
These files are a representation of the state groups and their predecessor links. 
They can be viewed in something like Gephi.

Added option to output directed graphs of the group heirarchy before and after compression

---

src/compressor.rs
src/database.rs
src/graphing.rs
src/lib.rs

BUILDS ON azren/added_graph_option (PR #43)
This allows the compressor to be called on only a selection of state groups in a room.
-b can be used to select the state group number to start compressing from 
(entering 0 or omitting this will start at the first state_group in the room)
-n can be used to enter (roughly) how many state groups you wish to compress. 
The compressor will print to stdout where it got up to. Entering this state group number
on the next run of the compressor will start from where the previous run finished
(NOTE: chunking produces worse compression than running all in one go, but will save memory)

Added option to only run the compressor on a range of state groups in a room

---

README.md
src/lib.rs

BUILDS ON azren/integration_tests
Documented all running options in README
The same help is also printed when running from command line with --help

Add information on running options to README and --help output

---

src/lib.rs

BUILDS ON azren/all_options_readme_and_help
This aborts the run of the compressor if it will lead to MORE rows in the database
This will prevent accidently running the generated SQL on the database and increasing storage requirements.

Aborts the run of the compressor if it will lead to more rows in the database

---

src/lib.rs

BUILDS ON azren/continuing_run
Moved the graph generation to before early exit
If the tool is making the tables bigger than they were before then
the compressor aborts the run. However if you wanted to debug this
by looking at before and after graphs of the chunk being compressed
then these need to be generated before it exits early.

Move the graph generation to before early exit

---

src/lib.rs
src/main.rs

This enables other packages to use the compressor without jemalloc

Move setting up jemalloc out of library crate

---

src/compressor.rs
src/compressor/compressor_tests.rs
src/compressor/level_tests.rs
src/database.rs
src/lib.rs
src/main.rs

The word current was tripping me up occasionally and since Levels are basically just lists, 
it makes sense to call it "head".
Getters added so that Level struct contents can be accessed from other packages
but not written to

Rename level current to head

---

compressor_integration_tests/tests/compressor_continue_run_tests.rs
src/compressor.rs
src/compressor/compressor_tests.rs
src/compressor/level_tests.rs
src/database.rs
src/lib.rs
src/main.rs

Also allow `groups_to_compress` to be used if `min_state_group` is None
(previously had to set it to something like -1 which was ugly)

Don't panic in continue_run if no groups found within range  

---

Cargo.lock
Cargo.toml
auto_compressor/Cargo.toml
auto_compressor/src/lib.rs
auto_compressor/src/state_saving.rs
compressor_integration_tests/Cargo.toml
compressor_integration_tests/src/lib.rs
compressor_integration_tests/tests/auto_compressor_state_saving_tests.rs
compressor_integration_tests/tests/compressor_continue_run_tests.rs
src/compressor.rs
src/compressor/compressor_tests.rs
src/compressor/level_tests.rs
src/database.rs
src/lib.rs
src/main.rs

Add new package with methods to save and load compressor state

---

auto_compressor/Cargo.toml
auto_compressor/src/manager.rs
auto_compressor/src/state_saving.rs
compressor_integration_tests/src/lib.rs
compressor_integration_tests/tests/auto_compressor_manager_tests.rs
src/database.rs

This is an alternative to #65 which compressed the rooms with the most uncompressed data.
This way won't work on the largest rooms first, so it might take longer to get the same space savings, but it doesn't need to count the number of rows in state_groups_state which would have taken a long time if a room hadn't been compressed before and had a lot of state.

Add method that compresses the chunks with lowest uncompressed state_group ids

---

Cargo.lock
Cargo.toml
compressor_integration_tests/src/lib.rs
compressor_integration_tests/tests/auto_compressor_state_saving_tests.rs
compressor_integration_tests/tests/compressor_config_tests.rs
compressor_integration_tests/tests/compressor_continue_run_tests.rs
src/database.rs
src/lib.rs
src/main.rs

Builds on #66 
The output from the manual tool is unchanged (since the logging is set to have no preamble)
but will allow the autocompressor to ignore some of the output, and format it nicely

Replace printing with logging

---

Cargo.lock
README.md
auto_compressor/Cargo.toml
auto_compressor/src/main.rs

Auto compressor for some reason was configured to log to a file. Now it just outputs to stderr.
The output can always just be piped to a file!

Log to stderr not to a file

---

.dockerignore
Dockerfile

simple alpine based docker container with `synapse_compress_state` and `synapse_auto_compressor`.
Example:
docker run -it --rm -v /run/postgresql/.s.PGSQL.5432:/run/postgresql/.s.PGSQL.5432 registry.gitlab.com/mb-saces/rust-synapse-compress-state:testing synapse_auto_compressor -p "postgresql://db_user:db_password@%2Frun%2Fpostgresql/synapse" -n 100 -c 500
My work repos lives here: https://gitlab.com/mb-saces/rust-synapse-compress-state

add docker files

---

synapse_auto_compressor/src/main.rs

PR #74 (Log to stderr not to a file) did not remove all references to
log_file, the file was still created, but remained empty.
The synapse_auto_compressor failed if run in a read only environment.

remove log_file leftovers

---

Cargo.lock
Cargo.toml
compressor_integration_tests/tests/compressor_config_tests.rs
compressor_integration_tests/tests/compressor_continue_run_tests.rs
src/compressor.rs
src/compressor/compressor_tests.rs
src/compressor/level_tests.rs
src/compressor/stats_tests.rs
src/database.rs
src/lib.rs
synapse_auto_compressor/Cargo.toml
synapse_auto_compressor/src/main.rs

- Fix clippy warnings encountered with current Rust.
- Update all dependencies.
- Updating `pyo3`, `clap` and `tikv-jemallocator` required touching `Cargo.toml` files.
- Updating `clap` required code changes.

Fix clippy warnings, update dependencies

---

Cargo.lock
Cargo.toml
compressor_integration_tests/src/lib.rs
src/compressor.rs
src/database.rs
src/lib.rs

- Fix more clippy warnings encountered with current Rust.
- Update all dependencies.
- Updating `indicatif` required code changes.

Fix clippy warnings, update dependencies (again)

---

synapse_auto_compressor/Cargo.toml
synapse_auto_compressor/src/main.rs

this allows me to build & run on OpenBSD (`cargo build --no-default-features`), where jemalloc doesnt build as is (build failure on some linux-only cpuset structs iirc) and the default system allocator performance is sufficient.
it compressed some states but didnt shrink that much my 3gb/15m records states database, i had to drop some room history.
diff from @semarie, pushing it on his behalf.

make jemalloc dependency really optional

---

Cargo.lock
Cargo.toml
compressor_integration_tests/Cargo.toml
src/lib.rs
synapse_auto_compressor/Cargo.toml
synapse_auto_compressor/src/lib.rs
synapse_auto_compressor/src/main.rs

- Fix a clippy warning in the auto compressor.
- Update all dependencies.
- Updating `clap` required code changes.

Fix clippy warnings, update dependencies (3)

---

README.md

An update to the docs as a follow-on from this issue: https://github.com/matrix-org/rust-synapse-compress-state/issues/110.

Update READ.me with information about Rust minimum version

---

.github/workflows/docker.yaml
Dockerfile

Adds a Github Actions workflow to publish containers on merges to main and when new tags are pushed.
As part of the change, cargo will now use the release when building the published containers, but default to the dev profile when building the container locally.
To fully configure this CI pipeline, there will need to be two Github Actions secrets added:
- `DOCKERHUB_USERNAME` set to matrixdotorg
- `DOCKERHUB_TOKEN` set to an API key capable of pushing to a `matrixdotorg/rust-synapse-compress-state` Docker Hub repository
The CI will automatically start pushing to both GHCR and Docker Hub.
I've validated the CI works on my own fork of this repo. See [this job](https://github.com/thefirstofthe300/rust-synapse-compress-state/actions/runs/4974855941/jobs/8901551770) for a full run. …

Add CI to publish official container

---

README.md

The README.md file states that the `-d` flag should be used to provide the size of the levels, instead, the code requires the `-l` flag https://github.com/matrix-org/rust-synapse-compress-state/blob/982ee5ead839938c90fa5d0ac871ae31393ba891/synapse_auto_compressor/src/main.rs#L91.

Fix README.md stating the wrong flag for levels

---

README.md

Add a second example to illustrate how to run the tool with a local PostgreSQL socket. This could discourage users from adding a password to their database.
I have successfully tested this commad on NixOS (using official matrix-synapse NixOS module). This should also work on Debian-based setups.

Add local PostgreSQL socket example to README

---

.github/workflows/docker.yaml

We should now have access to the relevant secrets.

Re-enable pushing to dockerhub

---

synapse_auto_compressor/Cargo.toml
synapse_auto_compressor/pyproject.toml

Otherwise maturin 1.5.0 won't let you publish.

Move python metadata to pyproject.toml

---

Cargo.lock
Cargo.toml
compressor_integration_tests/Cargo.toml

Given how [rust-matrix-state-map](https://github.com/matrix-org/rust-matrix-state-map) hasn't had an update in six years and all other dependencies of this software are pinned, I think it's safe and a good idea to pin this version too. This will also help with packaging efforts downstream, for example in https://github.com/NixOS/nixpkgs/pull/303704.

Pin state-map dependency on latest commit

---

.github/workflows/tests.yaml
Cargo.lock
Cargo.toml
compressor_integration_tests/Cargo.toml
docs/python.md
src/lib.rs
synapse_auto_compressor/Cargo.toml
synapse_auto_compressor/src/lib.rs
synapse_auto_compressor/src/main.rs

- Update all dependencies so that `cargo outdated -R` is satisfied.
- Use declarative pyo3 modules.
- The docs and the code disagreed on whether the auto compressor entry point is named `compress_largest_rooms`, `compress_state_events_table` or `compress_chunks_of_database`.
Rename the entry point to `run_compression`, matching the manual compressor, and fix the docs. Leave `compress_largest_rooms` as another entry point to avoid breaking existing code.
- Provide a default for `default_levels`.
- Use `&str` instead of `String` in Python signatures where it simplifies the code or is necessary to include the default in the text signature.
- Release the GIL while running the manual compressor.
- Use `map_err` to simplify error conversion a bit.

Update dependencies and improve pyo3

---

Cargo.lock
Cargo.toml
compressor_integration_tests/Cargo.toml
compressor_integration_tests/src/lib.rs
src/database.rs
src/graphing.rs
src/lib.rs
src/main.rs
synapse_auto_compressor/Cargo.toml
synapse_auto_compressor/src/lib.rs

Contains the following commits:
- **Modernize `Cargo.toml` files**    
Collect all dependency versions and some other info in the workspace
root.
- **Fix Clippy warnings with Rust 1.86.0**    
- **Update `rand` to 0.9.0**    
- **Update dependencies**    
Signed-off-by: Jan Alexander Steffens (heftig) <heftig@archlinux.org>

Fix clippy warnings, update dependencies (5)

---

.github/workflows/docker.yaml

This broke very quietly in https://github.com/matrix-org/rust-synapse-compress-state/pull/158 (See https://github.com/matrix-org/rust-synapse-compress-state/actions/runs/16938635005). So the first commit fixes the syntax.
The second commit changes the solution completely, as apparently `exit 0` [will not skip the rest of the job](https://github.com/matrix-org/rust-synapse-compress-state/actions/runs/16961790179/job/48076133728). Instead, we need to do a bunch of `if`s.

Correct syntax in docker.yaml workflow

---

.github/workflows/docker.yaml
.github/workflows/tests.yaml
.github/workflows/triage_incoming.yml
.github/workflows/triage_labelled.yml

Update and pin all of our GitHub Actions dependencies.
We're seeing [quite a lot of warnings](https://github.com/matrix-org/rust-synapse-compress-state/actions/runs/16961864694?pr=159) coming from the `rust-cache` crate (which is woefully out of date). The errors link to a GitHub deprecation blog post from 2022: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
So it's probably time we updated these dependencies. Pinning them also protects against supply chain attacks.
Requires https://github.com/matrix-org/rust-synapse-compress-state/pull/159.

Update and pin GitHub Actions deps
